Add fullscreen functionality
Robbendebiene/Gesturefy pull request #653
Opened 2022-09-18 06:21 UTC by Agha-Shadi

When you head to the _Gesturefy settings>Extras_ and set these settings up:

wheel gesture = 'On'
wheel gesture mouse button = 'right'
wheel up = 'Toggle full screen'
wheel down =  'Toggle full screen'

Afterwards whenever you hold down the right click and scroll up, you repeatedly toggle the full screen up and down because you usually scroll the wheel rather than rolling it just as much as a single upward movement. Thus you usually get back to the screen size that you were already using and the window size is not properly toggled yet. that can be solved if we have a single "Full Screen" option which sets the window to full screen. then we can set the _Gesturefy settings>Extras_ like this:

wheel gesture = 'On'
wheel gesture mouse button = 'right'
wheel up = 'full screen'
wheel down =  'Maximize window'

now you'll never face that problem ever again.

![After](https://user-images.githubusercontent.com/29219050/190888656-71c24006-c050-4892-b93d-478bdcd3fa5a.png)
![Before](https://user-images.githubusercontent.com/29219050/190888658-28adada4-5c13-4e88-99ef-bb129d77f2b7.png)

2022-09-19 18:57 UTC, Robbendebiene requested changes
Thanks for your pull request.
I'd prefer some changes in order to stay consistent with the other commands and generel conventions.

2022-09-19 18:57 UTC, Robbendebiene commented on src/core/commands.mjs
> +}
Please have a look at the `MaximizeWindow` command implementation.
If the window is already in fullscreen mode the function should not return true.

2022-09-19 18:57 UTC, Robbendebiene commented on src/resources/json/commands.json
> +    "group": "window"
The command is better suited for the `window.controls` group.

2022-09-19 18:57 UTC, Robbendebiene commented on src/_locales/en/messages.json
> +  "commandLabelFullscreen": {
Please rename the command and all it's occurrences from `Fullscreen` to `EnterFullscreen` or "Enter full screen" respectively.

2022-09-19 18:57 UTC, Robbendebiene commented on src/core/commands.mjs
> +
Please remove unnecessary indents.

2022-09-19 18:57 UTC, Robbendebiene commented on src/_locales/en/messages.json
> +    "description": "Sets the window to its full size."
Please change the description to: "Activates full screen mode for the current window." The main reason for this change is that "full size" might be misunderstood as "maximize the window"

2024-02-16 05:39 UTC, closed without merging

2024-02-16 05:39 UTC, M4K14 commented
added another pull request with fixes and updates. thanks for the instructions.